version: 0.0
os: linux
files:
  - source: /static_assets/website/*
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/pipeline/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/pipeline/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/pipeline/stop_server
      timeout: 300
      runas: root

